spring:
  application:
    name: taskManager

  datasource:
    # Если  через docker-compose, здесь должно быть 'db', а не 'localhost'
    url: jdbc:postgresql://db:5432/taskmanager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080


# Настройка логирования

logging:
  file:
    name: logs/application.log  # Путь к файлу логов
  level:
    root: INFO                  # Базовый уровень для всех библиотек
    com.javarush.ustinova.taskmanager: DEBUG  # Для кода детальные логи
    org.springframework.security: WARN


#  Актуатор

management:
  endpoints:
    web:
      exposure:
        # открытие эндпоинтов
        include: health, info, metrics, prometheus